matrix:
- name: asciidoc source py spell check configuration
  aspell:
    lang: en
    d: en_US
  sources:
  - documentation/*.asciidoc 
  dictionary:
    wordlists:
    - en-devonfw.dict
    output:  en-devonfw.dic
  pipeline:
  #Ignore for directory path
  - pyspelling.filters.context_filter: 
      context_visible_first: true
      escapes: '^.*[\/\\][^\/\\]+$'
      delimiters:
      #Ignore for url starting with http or https
      - open: 'https?:\S+?'
        close: '\s'
      #Ignore content between backticks
      - open: '```'
        close: '(\w|\W)+?(?=```)'
      #Ignore content between backticks
      - open: '(?<!``)`[^`]+'
        close: '`'
      #Ignore links
      - open: 'link:[^[]+'
        close: '\['
      #Ignore Image tags
      - open: 'image:[^[]+'
        close: '\['
      #Ignore Image tags link part
      - open: ',.+?link=[^\]]+'
        close: '\]'
      #Ignore include tag
      - open: 'include:[^[]+'
        close: '\['
      # Ignore multiline content between fences (fences can have 4 or more hyphens)
      # ----
      # content
      # ----
      # escapes: \\[\\-~]
      - open: '(?s)^(?P<open> *-{4,})$'
        close: '^(?P=open)$'  
      # Ignore multiline content between [source, *] and blank line
      - open: '\[source,.*\]\r?\n\s*----'
        close: '\s*----'
