matrix:
- name: asciidoc source py spell check configuration
  aspell:
    lang: en
  sources:
  - documentation/*.asciidoc 
  dictionary:
    wordlists:
    - en-devonfw.dict
    output:  en-devonfw.dic
  pipeline:
  #Ignore asciidoc options and flags
  - pyspelling.filters.context: 
      context_visible_first: true
      delimiters:
      - open: '^:'
        close: '$'
  #Ignore code blocks
  - pyspelling.filters.context: 
      context_visible_first: true
      delimiters:
      - open: '(?s)^```'
        close: '^```'
  #Ignore inline code
  - pyspelling.filters.context: 
      context_visible_first: true
      delimiters:
      - open: '(?<!``)`'
        close: '`'
  #Ignore links
  - pyspelling.filters.context: 
      context_visible_first: true
      delimiters:
      - open: '(link|xref):[^\[]+'
        close: '\['
  #Ignore Image tags
  - pyspelling.filters.context: 
      context_visible_first: true
      delimiters:
      - open: '(image|include):'
        close: '\]'
  # Ignore multiline content between [source, *] and ---- fences
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      - open: '(?s)^(\[source(,[^\]]*)?\]$)?\s*^----+'
        close: '^\s*----+'
  # Ignore multiline content between [source, *] and blank line
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      - open: '(?s)^\[source(,[^\]]*)?\]$'
        close: '^\s*$'
  #Ignore for url starting with http or https
  - pyspelling.filters.context: 
      context_visible_first: true
      delimiters:
      - open: 'https?:\S+?'
        close: '\s'
